### ISSUE TITLE
Decoding Error

### ISSUE THREAD

**Issue by danfowler** [frictionlessdata/goodtables-py#172]
`data/MetObjects.csv` is the dump from processing pipeline in [datapackage-pipelines](https://github.com/frictionlessdata/datapackage-pipelines)  cc: @akariv .  Original file here: https://github.com/metmuseum/openaccess

Good Tables version: 1.0.0-alpha5

```
(demo) legend:metmuseum-openaccess dan$ goodtables --row-limit 1000000 table data/MetObjects.csv 
Traceback (most recent call last):
  File "/Users/dan/open_knowledge/_envs/demo/bin/goodtables", line 11, in <module>
    sys.exit(cli())
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/goodtables/cli.py", line 47, in table
    report = ctx.obj['inspector'].inspect(source, preset='table', **options)
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/goodtables/inspector.py", line 102, in inspect
    report = task.get()
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/goodtables/inspector.py", line 205, in __inspect_table
    for row_number, headers, row in stream.iter(extended=True):
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/tabulator/stream.py", line 258, in iter
    for number, headers, row in iterator:
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/tabulator/stream.py", line 397, in builtin_processor
    for number, headers, row in extended_rows:
  File "/Users/dan/open_knowledge/_envs/demo/lib/python3.6/site-packages/tabulator/parsers/csv.py", line 90, in __iter_extended_rows
    for number, item in enumerate(items, start=1):
  File "/usr/local/bin/../Cellar/python3/3.6.0/bin/../Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 4071: character maps to <undefined>
```

**Comment by roll** [comment]
Fixed in `v1.0.0-alpha9`:

```
$ python -m goodtables.cli table https://media.githubusercontent.com/media/metmuseum/openaccess/master/MetObjects.csv
...report...
```

@danfowler 
If fails other file could you please attach and re-open.
