### ISSUE TITLE
Check minimum constrain fails with invalid operation

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-py#232]
# Overview

 python -m goodtables.cli https://raw.githubusercontent.com/Stephen-Gates/data-package-examples/master/test-number/datapackage.json
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/roll/projects/goodtables-py/goodtables/cli.py", line 71, in <module>
    cli()
  File "/home/roll/projects/goodtables-py/.python/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/roll/projects/goodtables-py/.python/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/roll/projects/goodtables-py/.python/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/roll/projects/goodtables-py/.python/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/roll/projects/goodtables-py/goodtables/cli.py", line 34, in cli
    report = goodtables.validate(source, **options)
  File "/home/roll/projects/goodtables-py/goodtables/validate.py", line 56, in validate
    report = inspector.inspect(source, preset=preset, **options)
  File "/home/roll/projects/goodtables-py/goodtables/inspector.py", line 80, in inspect
    table_warnings, table_report = task.get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/roll/projects/goodtables-py/goodtables/inspector.py", line 214, in __inspect_table
    check_func(errors, cells, row_number)
  File "/home/roll/projects/goodtables-py/goodtables/checks/minimum_constraint.py", line 22, in minimum_constraint
    valid = cell['field'].test_value(cell['value'], constraints=['minimum'])
  File "/home/roll/projects/goodtables-py/.python/lib/python3.5/site-packages/tableschema/field.py", line 108, in test_value
    self.cast_value(value, constraints=constraints)
  File "/home/roll/projects/goodtables-py/.python/lib/python3.5/site-packages/tableschema/field.py", line 95, in cast_value
    passed = check(cast_value)
  File "/home/roll/projects/goodtables-py/.python/lib/python3.5/site-packages/tableschema/constraints/minimum.py", line 13, in check_minimum
    if value >= constraint:
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]

**Comment by roll** [comment]
FIXED in #363
