### ISSUE TITLE
UnicodeDecodeError when initializing a datapackage with "goodtables init"

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/goodtables-py#257]
The data I'm using is http://opendatastore.brussels/dataset/e083a504-7ce9-4f76-b0b7-0e64b8469c3b/resource/5407e011-09f9-4adf-ad68-c83eba751806/download/hotelsevolclean.csv. When running `goodtables init hotelsevolclean.csv`, I get:

```
Traceback (most recent call last):
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/bin/goodtables", line 11, in <module>
    load_entry_point('goodtables', 'console_scripts', 'goodtables')()
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/goodtables/cli.py", line 122, in init
    dp = goodtables.init_datapackage(paths)
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/goodtables/validate.py", line 107, in init_datapackage
    dp.infer(path)
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/datapackage-1.2.1-py3.6.egg/datapackage/package.py", line 196, in infer
    descriptor = resource.infer()
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/datapackage-1.2.1-py3.6.egg/datapackage/resource.py", line 259, in infer
    descriptor['schema'] = self.__get_table().infer()
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/tableschema-1.0.10-py3.6.egg/tableschema/table.py", line 146, in infer
    with self.__stream as stream:
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/tabulator-1.12.2-py3.6.egg/tabulator/stream.py", line 107, in __enter__
    self.open()
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/tabulator-1.12.2-py3.6.egg/tabulator/stream.py", line 210, in open
    self.__extract_sample()
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/tabulator-1.12.2-py3.6.egg/tabulator/stream.py", line 352, in __extract_sample
    row_number, headers, row = next(self.__parser.extended_rows)
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/tabulator-1.12.2-py3.6.egg/tabulator/parsers/csv.py", line 97, in __iter_extended_rows
    sample, dialect = self.__prepare_dialect(self.__chars)
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/site-packages/tabulator-1.12.2-py3.6.egg/tabulator/parsers/csv.py", line 108, in __prepare_dialect
    sample.append(next(stream))
  File "/home/vitor/Projetos/okfn/frictionlessdata/goodtables-py/env/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 28: invalid continuation byte
```

Curiously, validating the file via `goodtables --infer-schema hotelsevolclean.csv` runs fine. Possibly a bug on `datapackage.Package().infer()`

**Comment by vitorbaptista** [comment]
This bug is fixed by https://github.com/frictionlessdata/datapackage-py/pull/212, we just need to upgrade datapackage when that's merged.
