### ISSUE TITLE
Doesn't work with pip-autoremove

### ISSUE THREAD

**Issue by neilmcguigan** [frictionlessdata/goodtables-py#324]
# Overview

try pip-autoremove goodtables and you get this error:

Traceback (most recent call last):
  File "/home/xxx/PycharmProjects/biglambda/venv/bin/pip-autoremove", line 10, in <module>
    sys.exit(main())
  File "/home/xxx/PycharmProjects/biglambda/venv/lib/python3.6/site-packages/pip_autoremove.py", line 106, in main
    autoremove(args, yes=opts.yes)
  File "/home/xxx/PycharmProjects/biglambda/venv/lib/python3.6/site-packages/pip_autoremove.py", line 21, in autoremove
    dead = list_dead(names)
  File "/home/xxx/PycharmProjects/biglambda/venv/lib/python3.6/site-packages/pip_autoremove.py", line 29, in list_dead
    graph = get_graph()
  File "/home/xxx/PycharmProjects/biglambda/venv/lib/python3.6/site-packages/pip_autoremove.py", line 89, in get_graph
    for req in requires(dist):
  File "/home/xxx/PycharmProjects/biglambda/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 481, in get_distribution
  File "/home/xxx/PycharmProjects/biglambda/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 357, in get_provider
  File "/home/xxx/PycharmProjects/biglambda/venv/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg/pkg_resources/__init__.py", line 643, in find
pkg_resources.VersionConflict: (docutils 0.16 (/home/xxx/PycharmProjects/biglambda/venv/lib/python3.6/site-packages), Requirement.parse('docutils<0.16,>=0.10'))

pip-autoremove works with other packages

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @neilmcguigan, could you please provide more context. For now, it's hard to say how it's related to `goodtables`.

**Comment by roll** [comment]
I'm closing as it's a `botocore` bug - https://github.com/boto/botocore/issues/1942 - hopefully, will be resolved soon
